---
- hosts: kubernetes_worker_nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src=$HOME/token.txt dest=join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat join_token | tail -2 > out.sh
     sh out.sh
